/**
 * Explicit permission catalogue. Code checks permissions, never role names.
 */
export const PERMISSIONS = [
  "company.view",
  "company.manage",
  "employee.view",
  "employee.create",
  "employee.edit",
  "employee.archive",
  "employee.delete",
  "salary.view",
  "salary.edit",
  "leave.view",
  "leave.request",
  "leave.approve",
  "leave.adjust",
  "leave.configure",
  "documents.view",
  "documents.upload",
  "documents.delete",
  "attendance.view",
  "attendance.edit",
  "attendance.approve",
  "workflows.manage",
  "payroll.view",
  "payroll.create",
  "payroll.calculate",
  "payroll.approve",
  "payroll.finalize",
  "payroll.lock",
  "payroll.reopen",
  "payroll.correct",
  "statutory_rules.view",
  "statutory_rules.edit",
  "statutory_rules.approve",
  "reports.hr",
  "reports.payroll",
  "reports.statutory",
  "accounting.export",
  "imports.run",
  "users.manage",
  "roles.manage",
  "audit.view",
  "billing.manage",
  "self.view",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const PERMISSION_GROUPS: { label: string; permissions: Permission[] }[] = [
  { label: "Company", permissions: ["company.view", "company.manage"] },
  {
    label: "Employees",
    permissions: ["employee.view", "employee.create", "employee.edit", "employee.archive", "employee.delete"],
  },
  { label: "Compensation", permissions: ["salary.view", "salary.edit"] },
  { label: "Leave", permissions: ["leave.view", "leave.request", "leave.approve", "leave.adjust", "leave.configure"] },
  { label: "Documents", permissions: ["documents.view", "documents.upload", "documents.delete"] },
  { label: "Attendance", permissions: ["attendance.view", "attendance.edit", "attendance.approve"] },
  { label: "Onboarding & offboarding", permissions: ["workflows.manage"] },
  {
    label: "Payroll",
    permissions: [
      "payroll.view",
      "payroll.create",
      "payroll.calculate",
      "payroll.approve",
      "payroll.finalize",
      "payroll.lock",
      "payroll.reopen",
      "payroll.correct",
    ],
  },
  { label: "Statutory rules", permissions: ["statutory_rules.view", "statutory_rules.edit", "statutory_rules.approve"] },
  { label: "Reports & exports", permissions: ["reports.hr", "reports.payroll", "reports.statutory", "accounting.export"] },
  { label: "Administration", permissions: ["imports.run", "users.manage", "roles.manage", "audit.view", "billing.manage"] },
  { label: "Self-service", permissions: ["self.view"] },
];

export const PERMISSION_LABELS: Record<Permission, string> = {
  "company.view": "View company profile",
  "company.manage": "Manage company settings",
  "employee.view": "View employee records",
  "employee.create": "Add employees",
  "employee.edit": "Edit employee records",
  "employee.archive": "Archive employees",
  "employee.delete": "Delete employees",
  "salary.view": "View salary and pay rates",
  "salary.edit": "Change salary and pay rates",
  "leave.view": "View leave",
  "leave.request": "Request leave",
  "leave.approve": "Approve leave",
  "leave.adjust": "Adjust leave balances",
  "leave.configure": "Configure leave types and policies",
  "documents.view": "View documents",
  "documents.upload": "Upload documents",
  "documents.delete": "Delete documents",
  "attendance.view": "View attendance",
  "attendance.edit": "Enter and edit timesheets",
  "attendance.approve": "Approve timesheets and corrections",
  "workflows.manage": "Manage onboarding and offboarding",
  "payroll.view": "View payroll",
  "payroll.create": "Create payroll runs and inputs",
  "payroll.calculate": "Calculate payroll",
  "payroll.approve": "Approve payroll",
  "payroll.finalize": "Finalize payroll",
  "payroll.lock": "Lock payroll",
  "payroll.reopen": "Reopen locked payroll",
  "payroll.correct": "Create payroll corrections",
  "statutory_rules.view": "View statutory rules",
  "statutory_rules.edit": "Edit statutory rules",
  "statutory_rules.approve": "Approve statutory rules",
  "reports.hr": "HR reports",
  "reports.payroll": "Payroll reports",
  "reports.statutory": "Statutory reports",
  "accounting.export": "Accounting export",
  "imports.run": "Run spreadsheet imports",
  "users.manage": "Manage users",
  "roles.manage": "Manage roles",
  "audit.view": "View audit log",
  "billing.manage": "Manage billing",
  "self.view": "Self-service access",
};

const ALL: Permission[] = [...PERMISSIONS];

const HR_CORE: Permission[] = [
  "company.view",
  "employee.view",
  "employee.create",
  "employee.edit",
  "employee.archive",
  "leave.view",
  "leave.request",
  "leave.approve",
  "leave.adjust",
  "leave.configure",
  "documents.view",
  "documents.upload",
  "documents.delete",
  "attendance.view",
  "attendance.edit",
  "attendance.approve",
  "workflows.manage",
  "reports.hr",
  "imports.run",
  "self.view",
];

const PAYROLL_CORE: Permission[] = [
  "company.view",
  "employee.view",
  "salary.view",
  "salary.edit",
  "leave.view",
  "attendance.view",
  "attendance.edit",
  "attendance.approve",
  "payroll.view",
  "payroll.create",
  "payroll.calculate",
  "payroll.approve",
  "payroll.finalize",
  "payroll.lock",
  "payroll.correct",
  "statutory_rules.view",
  "statutory_rules.edit",
  "reports.payroll",
  "reports.statutory",
  "accounting.export",
  "imports.run",
  "self.view",
];

export interface SystemRoleDefinition {
  key: string;
  name: string;
  description: string;
  permissions: Permission[];
  defaultScope: "all" | "team" | "self";
}

export const SYSTEM_ROLES: SystemRoleDefinition[] = [
  {
    key: "owner",
    name: "Owner",
    description: "Full access to every company, setting, user and billing.",
    permissions: ALL,
    defaultScope: "all",
  },
  {
    key: "hr_payroll_admin",
    name: "HR & Payroll Admin",
    description: "Runs HR and payroll end to end. Cannot manage billing.",
    permissions: ALL.filter((p) => p !== "billing.manage"),
    defaultScope: "all",
  },
  {
    key: "hr_manager",
    name: "HR Manager",
    description: "Employee records, leave, documents and onboarding. No salary or payroll access unless granted.",
    permissions: [...HR_CORE, "audit.view"],
    defaultScope: "all",
  },
  {
    key: "payroll_officer",
    name: "Payroll Officer",
    description: "Prepares, calculates and approves payroll. Cannot reopen locked payroll.",
    permissions: PAYROLL_CORE,
    defaultScope: "all",
  },
  {
    key: "supervisor",
    name: "Supervisor",
    description: "Sees assigned employees, approves their leave and timesheets. No salary or payroll access.",
    permissions: [
      "employee.view",
      "leave.view",
      "leave.request",
      "leave.approve",
      "attendance.view",
      "attendance.approve",
      "documents.view",
      "self.view",
    ],
    defaultScope: "team",
  },
  {
    key: "accountant",
    name: "Accountant / Auditor",
    description: "Read-only access to payroll, statutory reports, accounting export and the audit log.",
    permissions: [
      "company.view",
      "employee.view",
      "salary.view",
      "payroll.view",
      "statutory_rules.view",
      "reports.payroll",
      "reports.statutory",
      "accounting.export",
      "audit.view",
      "self.view",
    ],
    defaultScope: "all",
  },
  {
    key: "employee",
    name: "Employee",
    description: "Self-service: own profile, leave, payslips, documents and attendance.",
    permissions: ["self.view", "leave.request"],
    defaultScope: "self",
  },
];
