/**
 * Single icon entry point. All icons come from the Hugeicons free Stroke Rounded
 * set and render at one of three sizes with a consistent stroke.
 */
import { HugeiconsIcon, type IconSvgElement } from "@hugeicons/react";
import {
  Add01Icon,
  AlertCircleIcon,
  Alert02Icon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  ArrowUpRight01Icon,
  BankIcon,
  Building03Icon,
  BirthdayCakeIcon,
  Briefcase01Icon,
  Calculator01Icon,
  Calendar03Icon,
  Cancel01Icon,
  CheckListIcon,
  CheckmarkCircle02Icon,
  Clock01Icon,
  CommandIcon,
  Coins01Icon,
  Copy01Icon,
  Delete02Icon,
  Download04Icon,
  DashboardSquare01Icon,
  Edit02Icon,
  File02Icon,
  FileImportIcon,
  FilterIcon,
  Folder01Icon,
  HierarchyIcon,
  InformationCircleIcon,
  Invoice01Icon,
  LockIcon,
  LockKeyIcon,
  Logout03Icon,
  Mail01Icon,
  Menu01Icon,
  MoreHorizontalIcon,
  Note01Icon,
  PercentIcon,
  Refresh01Icon,
  Search01Icon,
  Settings02Icon,
  Shield01Icon,
  SidebarLeftIcon,
  SortByDown01Icon,
  SortByUp01Icon,
  Tick02Icon,
  Upload04Icon,
  UserAdd01Icon,
  UserGroupIcon,
  UserIcon,
  UserSwitchIcon,
  ViewIcon,
  Wallet01Icon,
  ChartColumnIcon,
  CreditCardIcon,
  TaskDone01Icon,
  Award01Icon,
  ArrowExpand01Icon,
  Unlink01Icon,
  CircleLock01Icon,
  ReceiptDollarIcon,
  Book02Icon,
  PrinterIcon,
  LinkSquare01Icon,
  Database01Icon,
  ZipIcon,
} from "@hugeicons/core-free-icons";
import { cn } from "@/lib/cn";

export const icons = {
  add: Add01Icon,
  alert: AlertCircleIcon,
  warning: Alert02Icon,
  chevronDown: ArrowDown01Icon,
  chevronLeft: ArrowLeft01Icon,
  chevronRight: ArrowRight01Icon,
  chevronUp: ArrowUp01Icon,
  external: ArrowUpRight01Icon,
  bank: BankIcon,
  building: Building03Icon,
  birthday: BirthdayCakeIcon,
  briefcase: Briefcase01Icon,
  calculator: Calculator01Icon,
  calendar: Calendar03Icon,
  close: Cancel01Icon,
  checklist: CheckListIcon,
  success: CheckmarkCircle02Icon,
  clock: Clock01Icon,
  command: CommandIcon,
  coins: Coins01Icon,
  copy: Copy01Icon,
  delete: Delete02Icon,
  download: Download04Icon,
  dashboard: DashboardSquare01Icon,
  edit: Edit02Icon,
  file: File02Icon,
  import: FileImportIcon,
  filter: FilterIcon,
  folder: Folder01Icon,
  hierarchy: HierarchyIcon,
  info: InformationCircleIcon,
  invoice: Invoice01Icon,
  lock: LockIcon,
  key: LockKeyIcon,
  logout: Logout03Icon,
  mail: Mail01Icon,
  menu: Menu01Icon,
  more: MoreHorizontalIcon,
  note: Note01Icon,
  percent: PercentIcon,
  refresh: Refresh01Icon,
  search: Search01Icon,
  settings: Settings02Icon,
  shield: Shield01Icon,
  sidebar: SidebarLeftIcon,
  sortDown: SortByDown01Icon,
  sortUp: SortByUp01Icon,
  check: Tick02Icon,
  upload: Upload04Icon,
  userAdd: UserAdd01Icon,
  users: UserGroupIcon,
  user: UserIcon,
  userSwitch: UserSwitchIcon,
  view: ViewIcon,
  wallet: Wallet01Icon,
  chart: ChartColumnIcon,
  card: CreditCardIcon,
  taskDone: TaskDone01Icon,
  award: Award01Icon,
  expand: ArrowExpand01Icon,
  unlink: Unlink01Icon,
  unlock: CircleLock01Icon,
  receipt: ReceiptDollarIcon,
  book: Book02Icon,
  print: PrinterIcon,
  link: LinkSquare01Icon,
  database: Database01Icon,
  zip: ZipIcon,
} satisfies Record<string, IconSvgElement>;

export type IconName = keyof typeof icons;

const SIZES = { sm: 14, md: 16, lg: 20 } as const;

export function Icon({ name, size = "md", className, label }: { name: IconName; size?: keyof typeof SIZES; className?: string; label?: string }) {
  return (
    <HugeiconsIcon
      icon={icons[name]}
      size={SIZES[size]}
      strokeWidth={1.7}
      className={cn("shrink-0", className)}
      aria-hidden={label ? undefined : true}
      aria-label={label}
      role={label ? "img" : undefined}
    />
  );
}
